// Arguments passed into this controller can be accessed via the `$.args` object directly or:
var args = $.args;
 console.log("This is child widow settings.js");
 $.settings.open();

function swipeLeft(s){
	console.log("setting.js: check swipeLeft stuff: "+JSON.stringify(s));
	if (s.direction =="left") {
		var direction = s.direction;
		alert("direction is: "+direction);
		var indexController = Alloy.createController('index').getView();
    	$.settings.open(indexController, 'fast');
	}
	
};
function openEditGoal(s){
	console.log("settings,js: check openEditGoal: "+JSON.stringify(s));
	var EditGoalController = Alloy.createController('editgoal').getView();
	$.settings.open(EditGoalController, "fast");
}
$.openeditgoal.addEventListener('click', openEditGoal);


var pages = [{"page": "1", "beginningAyat": "Al-Fatihah 1", "endingAyat": "al-Baqarah 1"},
			{"page": "2", "beginningAyat": "al-Baqarah 1", "endingAyat": "al-Baqarah 6"},
			{"page": "3", "beginningAyat": "al-Baqarah 6", "endingAyat": "al-Baqarah 17"},
			{"page": "4", "beginningAyat": "al-Baqarah 17", "endingAyat": "al-Baqarah 25"},
			{"page": "5", "beginningAyat": "al-Baqarah 25", "endingAyat": "al-Baqarah 30"},
			{"page": "6", "beginningAyat": "al-Baqarah 30", "endingAyat": "al-Baqarah 38"},
			{"page": "7", "beginningAyat": "al-Baqarah 38", "endingAyat": "al-Baqarah 49"},
			{"page": "8", "beginningAyat": "al-Baqarah 49", "endingAyat": "al-Baqarah 58"},
			{"page": "9", "beginningAyat": "al-Baqarah 58", "endingAyat": "al-Baqarah 62"},
			{"page": "10", "beginningAyat": "al-Baqarah 62", "endingAyat": "al-Baqarah 70"},
			{"page": "11", "beginningAyat": "al-Baqarah 70", "endingAyat": "al-Baqarah 77"},
			{"page": "12", "beginningAyat": "al-Baqarah 77", "endingAyat": "al-Baqarah 84"},
			{"page": "13", "beginningAyat": "al-Baqarah 84", "endingAyat": "al-Baqarah 90"},
			{"page": "14", "beginningAyat": "al-Baqarah 89", "endingAyat": "al-Baqarah 94"},
			{"page": "15", "beginningAyat": "al-Baqarah 94", "endingAyat": "al-Baqarah 102"},
			{"page": "16", "beginningAyat": "al-Baqarah 102", "endingAyat": "al-Baqarah 106"},
			{"page": "17", "beginningAyat": "al-Baqarah 106", "endingAyat": "al-Baqarah 113"},
			{"page": "18", "beginningAyat": "al-Baqarah 113", "endingAyat": "al-Baqarah 120"},
			{"page": "19", "beginningAyat": "al-Baqarah 120", "endingAyat": "al-Baqarah 127"},
			{"page": "20", "beginningAyat": "al-Baqarah 127", "endingAyat": "al-Baqarah 135"},
			{"page": "21", "beginningAyat": "al-Baqarah 135", "endingAyat": "al-Baqarah 142"},
			{"page": "22", "beginningAyat": "al-Baqarah 142", "endingAyat": "al-Baqarah 146"},
			{"page": "23", "beginningAyat": "al-Baqarah 146", "endingAyat": "al-Baqarah 154"},
			{"page": "24", "beginningAyat": "al-Baqarah 154", "endingAyat": "al-Baqarah 164"},
			{"page": "25", "beginningAyat": "al-Baqarah 164", "endingAyat": "al-Baqarah 170"},
			{"page": "26", "beginningAyat": "al-Baqarah 170", "endingAyat": "al-Baqarah 177"},
			{"page": "27", "beginningAyat": "al-Baqarah 177", "endingAyat": "al-Baqarah 182"},
			{"page": "28", "beginningAyat": "al-Baqarah 182", "endingAyat": "al-Baqarah 187"},
			{"page": "29", "beginningAyat": "al-Baqarah 187", "endingAyat": "al-Baqarah 191"},
			{"page": "30", "beginningAyat": "al-Baqarah 191", "endingAyat": "al-Baqarah 197"},
			{"page": "31", "beginningAyat": "al-Baqarah 197", "endingAyat": "al-Baqarah 203"},
			{"page": "32", "beginningAyat": "al-Baqarah 203", "endingAyat": "al-Baqarah 211"},
			{"page": "33", "beginningAyat": "al-Baqarah 211", "endingAyat": "al-Baqarah 216"},
			{"page": "34", "beginningAyat": "al-Baqarah 216", "endingAyat": "al-Baqarah 220"},
			{"page": "35", "beginningAyat": "al-Baqarah 220", "endingAyat": "al-Baqarah 225"},
			{"page": "36", "beginningAyat": "al-Baqarah 225", "endingAyat": "al-Baqarah 231"},
			{"page": "37", "beginningAyat": "al-Baqarah 231", "endingAyat": "al-Baqarah 234"},
			{"page": "38", "beginningAyat": "al-Baqarah 234", "endingAyat": "al-Baqarah 238"},
			{"page": "39", "beginningAyat": "al-Baqarah 238", "endingAyat": "al-Baqarah 246"},
			{"page": "40", "beginningAyat": "al-Baqarah 246", "endingAyat": "al-Baqarah 249"},
			{"page": "41", "beginningAyat": "al-Baqarah 249", "endingAyat": "al-Baqarah 253"},
			{"page": "42", "beginningAyat": "al-Baqarah 253", "endingAyat": "al-Baqarah 257"},
			{"page": "43", "beginningAyat": "al-Baqarah 257", "endingAyat": "al-Baqarah 260"},
			{"page": "44", "beginningAyat": "al-Baqarah 260", "endingAyat": "al-Baqarah 265"},
			{"page": "45", "beginningAyat": "al-Baqarah 265", "endingAyat": "al-Baqarah 270"},
			{"page": "46", "beginningAyat": "al-Baqarah 270", "endingAyat": "al-Baqarah 275"},
			{"page": "47", "beginningAyat": "al-Baqarah 275", "endingAyat": "al-Baqarah 282"},
			{"page": "48", "beginningAyat": "al-Baqarah 282", "endingAyat": "al-Baqarah 283"},
			{"page": "49", "beginningAyat": "al-Baqarah 283", "endingAyat": "Al-Imran 1"},
			{"page": "50", "beginningAyat": "Al-Imran 1", "endingAyat": "Al-Imran 10"},
			{"page": "51", "beginningAyat": "Al-Imran 10", "endingAyat": "Al-Imran 16"},
			{"page": "52", "beginningAyat": "Al-Imran 16", "endingAyat": "Al-Imran 23"},
			{"page": "53", "beginningAyat": "Al-Imran 23", "endingAyat": "Al-Imran 30"},
			{"page": "54", "beginningAyat": "Al-Imran 30", "endingAyat": "Al-Imran 38"},
			{"page": "55", "beginningAyat": "Al-Imran 38", "endingAyat": "Al-Imran 46"},
			{"page": "56", "beginningAyat": "Al-Imran 46", "endingAyat": "Al-Imran 53"},
			{"page": "57", "beginningAyat": "Al-Imran 53", "endingAyat": "Al-Imran 62"},
			{"page": "58", "beginningAyat": "Al-Imran 62", "endingAyat": "Al-Imran 71"},
			{"page": "59", "beginningAyat": "Al-Imran 71", "endingAyat": "Al-Imran 78"},
			{"page": "60", "beginningAyat": "Al-Imran 78", "endingAyat": "Al-Imran 84"},
			{"page": "61", "beginningAyat": "Al-Imran 84", "endingAyat": "Al-Imran 92"},
			{"page": "62", "beginningAyat": "Al-Imran 92", "endingAyat": "Al-Imran 101"},
			{"page": "63", "beginningAyat": "Al-Imran 101", "endingAyat": "Al-Imran 109"},
			{"page": "64", "beginningAyat": "Al-Imran 109", "endingAyat": "Al-Imran 116"},
			{"page": "65", "beginningAyat": "Al-Imran 116", "endingAyat": "Al-Imran 122"},
			{"page": "66", "beginningAyat": "Al-Imran 122", "endingAyat": "Al-Imran 133"},
			{"page": "67", "beginningAyat": "Al-Imran 133", "endingAyat": "Al-Imran 141"},
			{"page": "68", "beginningAyat": "Al-Imran 141", "endingAyat": "Al-Imran 149"},
			{"page": "69", "beginningAyat": "Al-Imran 149", "endingAyat": "Al-Imran 154"},
			{"page": "70", "beginningAyat": "Al-Imran 154", "endingAyat": "Al-Imran 158"},
			{"page": "71", "beginningAyat": "Al-Imran 158", "endingAyat": "Al-Imran 166"},
			{"page": "72", "beginningAyat": "Al-Imran 166", "endingAyat": "Al-Imran 174"},
			{"page": "73", "beginningAyat": "Al-Imran 174", "endingAyat": "Al-Imran 181"},
			{"page": "74", "beginningAyat": "Al-Imran 181", "endingAyat": "Al-Imran 187"},
			{"page": "75", "beginningAyat": "Al-Imran 187", "endingAyat": "Al-Imran 195"},
			{"page": "76", "beginningAyat": "Al-Imran 195", "endingAyat": "an-Nisa 1"},
			{"page": "77", "beginningAyat": "an-Nisa 1", "endingAyat": "an-Nisa 7"},
			{"page": "78", "beginningAyat": "an-Nisa 7", "endingAyat": "an-Nisa 12"},
			{"page": "79", "beginningAyat": "an-Nisa 12", "endingAyat": "an-Nisa 15"},
			{"page": "80", "beginningAyat": "an-Nisa 15", "endingAyat": "an-Nisa 20"},
			{"page": "81", "beginningAyat": "an-Nisa 20", "endingAyat": "an-Nisa 24"},
			{"page": "82", "beginningAyat": "an-Nisa 24", "endingAyat": "an-Nisa 27"},
			{"page": "83", "beginningAyat": "an-Nisa 27", "endingAyat": "an-Nisa 34"},
			{"page": "84", "beginningAyat": "an-Nisa 34", "endingAyat": "an-Nisa 38"},
			{"page": "85", "beginningAyat": "an-Nisa 38", "endingAyat": "an-Nisa 45"},
			{"page": "86", "beginningAyat": "an-Nisa 45", "endingAyat": "an-Nisa 52"},
			{"page": "87", "beginningAyat": "an-Nisa 52", "endingAyat": "an-Nisa 60"},
			{"page": "88", "beginningAyat": "an-Nisa 60", "endingAyat": "an-Nisa 66"},
			{"page": "89", "beginningAyat": "an-Nisa 66", "endingAyat": "an-Nisa 75"},
			{"page": "90", "beginningAyat": "an-Nisa 75", "endingAyat": "an-Nisa 80"},
			{"page": "91", "beginningAyat": "an-Nisa 80", "endingAyat": "an-Nisa 87"},
			{"page": "92", "beginningAyat": "an-Nisa 87", "endingAyat": "an-Nisa 92"},
			{"page": "93", "beginningAyat": "an-Nisa 92", "endingAyat": "an-Nisa 95"},
			{"page": "94", "beginningAyat": "an-Nisa 95", "endingAyat": "an-Nisa 102"},
			{"page": "95", "beginningAyat": "an-Nisa 102", "endingAyat": "an-Nisa 106"},
			{"page": "96", "beginningAyat": "an-Nisa 106", "endingAyat": "an-Nisa 114"},
			{"page": "97", "beginningAyat": "an-Nisa 114", "endingAyat": "an-Nisa 122"},
			{"page": "98", "beginningAyat": "an-Nisa 122", "endingAyat": "an-Nisa 128"},
			{"page": "99", "beginningAyat": "an-Nisa 128", "endingAyat": "an-Nisa 135"},
			{"page": "100", "beginningAyat": "an-Nisa 135", "endingAyat": "an-Nisa 141"},
			{"page": "101", "beginningAyat": "an-Nisa 141", "endingAyat": "an-Nisa 148"},
			{"page": "102", "beginningAyat": "an-Nisa 148", "endingAyat": "an-Nisa 155"},
			{"page": "103", "beginningAyat": "an-Nisa 155", "endingAyat": "an-Nisa 163"},
			{"page": "104", "beginningAyat": "an-Nisa 163", "endingAyat": "an-Nisa 171"},
			{"page": "105", "beginningAyat": "an-Nisa 171", "endingAyat": "an-Nisa 176"},
			{"page": "106", "beginningAyat": "an-Nisa 176", "endingAyat": "al-Maidah 3"},
			{"page": "107", "beginningAyat": "al-Maidah 3", "endingAyat": "al-Maidah 6"},
			{"page": "108", "beginningAyat": "al-Maidah 6", "endingAyat": "al-Maidah 10"},
			{"page": "109", "beginningAyat": "al-Maidah 10", "endingAyat": "al-Maidah 14"},
			{"page": "110", "beginningAyat": "al-Maidah 14", "endingAyat": "al-Maidah 18"},
			{"page": "111", "beginningAyat": "al-Maidah 18", "endingAyat": "al-Maidah 24"},
			{"page": "112", "beginningAyat": "al-Maidah 24", "endingAyat": "al-Maidah 32"},
			{"page": "113", "beginningAyat": "al-Maidah 32", "endingAyat": "al-Maidah 37"},
			{"page": "114", "beginningAyat": "al-Maidah 37", "endingAyat": "al-Maidah 42"},
			{"page": "115", "beginningAyat": "al-Maidah 42", "endingAyat": "al-Maidah 46"},
			{"page": "116", "beginningAyat": "al-Maidah 46", "endingAyat": "al-Maidah 51"},
			{"page": "117", "beginningAyat": "al-Maidah 51", "endingAyat": "al-Maidah 58"},
			{"page": "118", "beginningAyat": "al-Maidah 58", "endingAyat": "al-Maidah 65"},
			{"page": "119", "beginningAyat": "al-Maidah 65", "endingAyat": "al-Maidah 71"},
			{"page": "120", "beginningAyat": "al-Maidah 71", "endingAyat": "al-Maidah 77"},
			{"page": "121", "beginningAyat": "al-Maidah 77", "endingAyat": "al-Maidah 83"},
			{"page": "122", "beginningAyat": "al-Maidah 83", "endingAyat": "al-Maidah 90"},
			{"page": "123", "beginningAyat": "al-Maidah 90", "endingAyat": "al-Maidah 96"},
			{"page": "124", "beginningAyat": "al-Maidah 96", "endingAyat": "al-Maidah 104"},
			{"page": "125", "beginningAyat": "al-Maidah 104", "endingAyat": "al-Maidah 109"},
			{"page": "126", "beginningAyat": "al-Maidah 109", "endingAyat": "al-Maidah 114"},
			{"page": "127", "beginningAyat": "al-Maidah 114", "endingAyat": "al-Anam 1"},
			{"page": "128", "beginningAyat": "al-Anam 1", "endingAyat": "al-Anam 9"},
			{"page": "129", "beginningAyat": "al-Anam 9", "endingAyat": "al-Anam 19"},
			{"page": "130", "beginningAyat": "al-Anam 19", "endingAyat": "al-Anam 28"},
			{"page": "131", "beginningAyat": "al-Anam 28", "endingAyat": "al-Anam 36"},
			{"page": "132", "beginningAyat": "al-Anam 36", "endingAyat": "al-Anam 45"},
			{"page": "133", "beginningAyat": "al-Anam 45", "endingAyat": "al-Anam 53"},
			{"page": "134", "beginningAyat": "al-Anam 53", "endingAyat": "al-Anam 60"},
			{"page": "135", "beginningAyat": "al-Anam 60", "endingAyat": "al-Anam 69"},
			{"page": "136", "beginningAyat": "al-Anam 69", "endingAyat": "al-Anam 74"},
			{"page": "137", "beginningAyat": "al-Anam 74", "endingAyat": "al-Anam 82"},
			{"page": "138", "beginningAyat": "al-Anam 82", "endingAyat": "al-Anam 91"},
			{"page": "139", "beginningAyat": "al-Anam 91", "endingAyat": "al-Anam 95"},
			{"page": "140", "beginningAyat": "al-Anam 95", "endingAyat": "al-Anam 102"},
			{"page": "141", "beginningAyat": "al-Anam 102", "endingAyat": "al-Anam 111"},
			{"page": "142", "beginningAyat": "al-Anam 111", "endingAyat": "al-Anam 119"},
			{"page": "143", "beginningAyat": "al-Anam 119", "endingAyat": "al-Anam 125"},
			{"page": "144", "beginningAyat": "al-Anam 125", "endingAyat": "al-Anam 132"},
			{"page": "145", "beginningAyat": "al-Anam 135", "endingAyat": "al-Anam 138"},
			{"page": "146", "beginningAyat": "", "endingAyat": ""},
			{"page": "147", "beginningAyat": "", "endingAyat": ""},
			{"page": "148", "beginningAyat": "", "endingAyat": ""},
			{"page": "149", "beginningAyat": "", "endingAyat": ""},
			{"page": "150", "beginningAyat": "", "endingAyat": ""},
			{"page": "151", "beginningAyat": "", "endingAyat": ""},
			{"page": "152", "beginningAyat": "", "endingAyat": ""},
			{"page": "153", "beginningAyat": "", "endingAyat": ""},
			{"page": "154", "beginningAyat": "", "endingAyat": ""},
			{"page": "155", "beginningAyat": "", "endingAyat": ""},
			{"page": "156", "beginningAyat": "", "endingAyat": ""},
			{"page": "157", "beginningAyat": "", "endingAyat": ""},
			{"page": "158", "beginningAyat": "", "endingAyat": ""},
			{"page": "159", "beginningAyat": "", "endingAyat": ""},
			{"page": "160", "beginningAyat": "", "endingAyat": ""},
			{"page": "161", "beginningAyat": "", "endingAyat": ""},
			{"page": "162", "beginningAyat": "", "endingAyat": ""},
			{"page": "163", "beginningAyat": "", "endingAyat": ""},
			{"page": "164", "beginningAyat": "", "endingAyat": ""},
			{"page": "165", "beginningAyat": "", "endingAyat": ""},
			{"page": "166", "beginningAyat": "", "endingAyat": ""},
			{"page": "167", "beginningAyat": "", "endingAyat": ""},
			{"page": "168", "beginningAyat": "", "endingAyat": ""},
			{"page": "169", "beginningAyat": "", "endingAyat": ""},
			{"page": "170", "beginningAyat": "", "endingAyat": ""},
			{"page": "171", "beginningAyat": "", "endingAyat": ""},
			{"page": "172", "beginningAyat": "", "endingAyat": ""},
			{"page": "173", "beginningAyat": "", "endingAyat": ""},
			{"page": "174", "beginningAyat": "", "endingAyat": ""},
			{"page": "175", "beginningAyat": "", "endingAyat": ""},
			{"page": "176", "beginningAyat": "", "endingAyat": ""},
			{"page": "177", "beginningAyat": "", "endingAyat": ""},
			{"page": "178", "beginningAyat": "", "endingAyat": ""},
			{"page": "179", "beginningAyat": "", "endingAyat": ""},
			{"page": "180", "beginningAyat": "", "endingAyat": ""},
			{"page": "181", "beginningAyat": "", "endingAyat": ""},
			{"page": "182", "beginningAyat": "", "endingAyat": ""},
			{"page": "183", "beginningAyat": "", "endingAyat": ""},
			{"page": "184", "beginningAyat": "", "endingAyat": ""},
			{"page": "185", "beginningAyat": "", "endingAyat": ""},
			{"page": "186", "beginningAyat": "", "endingAyat": ""},
			{"page": "187", "beginningAyat": "", "endingAyat": ""},
			{"page": "188", "beginningAyat": "", "endingAyat": ""},
			{"page": "189", "beginningAyat": "", "endingAyat": ""},
			{"page": "190", "beginningAyat": "", "endingAyat": ""},
			{"page": "191", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""},
			{"page": "", "beginningAyat": "", "endingAyat": ""}


];


